apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DB_HOST: "{{ .Values.config.dbHost }}"
  DB_NAME: "{{ .Values.config.dbName }}"
  DB_USER: "{{ .Values.config.dbUser }}"
  DB_PORT: "{{ .Values.config.dbPort }}"
  APP_ENV: "{{ .Values.config.appEnv }}"
  BANNER_MESSAGE: "{{ .Values.config.banner }}"
