apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: readinglist-api
  namespace: matheus515-dev
spec:
  to:
    kind: Service
    name: readinglist-api
  port:
    targetPort: http
  tls:
    termination: edge
