apiVersion: apps/v1
kind: Deployment
metadata:
  name: readinglist-api
  namespace: matheus515-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: readinglist-api
  template:
    metadata:
      labels:
        app: readinglist-api
    spec:
      containers:
        - name: api
          image: docker.io/matheus515/readinglist:d891061d8269f771078241d64788246aa3b2b5e8
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: readinglist-config
            - secretRef:
                name: readinglist-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
